from Compiladores.constants import EPSILON

DeltaFinal = {
    #S
    ('S', 'K', EPSILON): ('B1,B2,Z', 'K'),
    ('S', 'L', EPSILON): ('B7,B8,Z', 'L'),
    ('S', 'H', EPSILON): ('B3,B6,Z', 'H'),
    ('S', 'N', EPSILON): ('B12,Z', 'N'),
    ('S', 'J', EPSILON): ('B4,Z', 'J'),
    ('S', 'F', EPSILON): ('B5,B7,B9,Z', 'F'),
    ('S', 'A', EPSILON): ('B10,B11,Z', 'A'),
    #CARACTERES QUE SÓ Z PEGA
    ('S', 'O', EPSILON): ('Z', 'O'),
    ('S', 'E', EPSILON): ('Z', 'E'),
    ('S', 'U', EPSILON): ('Z', 'U'),
    ('S', 'S', EPSILON): ('Z', 'S'),
    ('S', 'I', EPSILON): ('Z', 'I'),
    ('S', 'M', EPSILON): ('Z', 'M'),
    ('S', 'D', EPSILON): ('Z', 'D'),
    ('S', 'R', EPSILON): ('Z', 'R'),
    ('S', 'T', EPSILON): ('Z', 'T'),

    #B1,B2,Z
    ('B1,B2,Z', 'O', EPSILON): ('B1,Z', 'O'),
    ('B1,B2,Z', 'E', EPSILON): ('C2,Z', 'E'),
    #CARACTERES QUE SÓ Z PEGA
    ('B1,B2,Z', 'K', EPSILON): ('Z', 'K'),
    ('B1,B2,Z', 'L', EPSILON): ('Z', 'L'),
    ('B1,B2,Z', 'H', EPSILON): ('Z', 'H'),
    ('B1,B2,Z', 'N', EPSILON): ('Z', 'N'),
    ('B1,B2,Z', 'J', EPSILON): ('Z', 'J'),
    ('B1,B2,Z', 'U', EPSILON): ('Z', 'U'),
    ('B1,B2,Z', 'F', EPSILON): ('Z', 'F'),
    ('B1,B2,Z', 'S', EPSILON): ('Z', 'S'),
    ('B1,B2,Z', 'I', EPSILON): ('Z', 'I'),
    ('B1,B2,Z', 'M', EPSILON): ('Z', 'M'),
    ('B1,B2,Z', 'D', EPSILON): ('Z', 'D'),
    ('B1,B2,Z', 'R', EPSILON): ('Z', 'R'),
    ('B1,B2,Z', 'T', EPSILON): ('Z', 'T'),
    ('B1,B2,Z', 'A', EPSILON): ('Z', 'A'),

    #Z
    ('Z', 'O', EPSILON): ('Z', 'O'),
    ('Z', 'E', EPSILON): ('Z', 'E'),
    ('Z', 'K', EPSILON): ('Z', 'K'),
    ('Z', 'L', EPSILON): ('Z', 'L'),
    ('Z', 'H', EPSILON): ('Z', 'H'),
    ('Z', 'N', EPSILON): ('Z', 'N'),
    ('Z', 'J', EPSILON): ('Z', 'J'),
    ('Z', 'U', EPSILON): ('Z', 'U'),
    ('Z', 'F', EPSILON): ('Z', 'F'),
    ('Z', 'S', EPSILON): ('Z', 'S'),
    ('Z', 'I', EPSILON): ('Z', 'I'),
    ('Z', 'M', EPSILON): ('Z', 'M'),
    ('Z', 'D', EPSILON): ('Z', 'D'),
    ('Z', 'R', EPSILON): ('Z', 'R'),
    ('Z', 'T', EPSILON): ('Z', 'T'),
    ('Z', 'A', EPSILON): ('Z', 'A'),

    #B7,B8,Z
    ('B7,B8,Z', 'O', EPSILON): ('C8,Z', 'O'),
    ('B7,B8,Z', 'A', EPSILON): ('C7,Z', 'A'),
    #CARACTERES QUE SÓ Z PEGA
    ('B7,B8,Z', 'K', EPSILON): ('Z', 'K'),
    ('B7,B8,Z', 'E', EPSILON): ('Z', 'E'),
    ('B7,B8,Z', 'L', EPSILON): ('Z', 'L'),
    ('B7,B8,Z', 'H', EPSILON): ('Z', 'H'),
    ('B7,B8,Z', 'N', EPSILON): ('Z', 'N'),
    ('B7,B8,Z', 'J', EPSILON): ('Z', 'J'),
    ('B7,B8,Z', 'U', EPSILON): ('Z', 'U'),
    ('B7,B8,Z', 'F', EPSILON): ('Z', 'F'),
    ('B7,B8,Z', 'S', EPSILON): ('Z', 'S'),
    ('B7,B8,Z', 'I', EPSILON): ('Z', 'I'),
    ('B7,B8,Z', 'M', EPSILON): ('Z', 'M'),
    ('B7,B8,Z', 'D', EPSILON): ('Z', 'D'),
    ('B7,B8,Z', 'R', EPSILON): ('Z', 'R'),
    ('B7,B8,Z', 'T', EPSILON): ('Z', 'T'),

    #B3,B6,Z
    ('B3,B6,Z', 'O', EPSILON): ('C3,Z', 'O'),
    ('B3,B6,Z', 'I', EPSILON): ('C6,Z', 'I'),
    #CARACTERES QUE SÓ Z PEGA
    ('B3,B6,Z', 'K', EPSILON): ('Z', 'K'),
    ('B3,B6,Z', 'E', EPSILON): ('Z', 'E'),
    ('B3,B6,Z', 'L', EPSILON): ('Z', 'L'),
    ('B3,B6,Z', 'H', EPSILON): ('Z', 'H'),
    ('B3,B6,Z', 'N', EPSILON): ('Z', 'N'),
    ('B3,B6,Z', 'J', EPSILON): ('Z', 'J'),
    ('B3,B6,Z', 'U', EPSILON): ('Z', 'U'),
    ('B3,B6,Z', 'F', EPSILON): ('Z', 'F'),
    ('B3,B6,Z', 'S', EPSILON): ('Z', 'S'),
    ('B3,B6,Z', 'M', EPSILON): ('Z', 'M'),
    ('B3,B6,Z', 'D', EPSILON): ('Z', 'D'),
    ('B3,B6,Z', 'R', EPSILON): ('Z', 'R'),
    ('B3,B6,Z', 'T', EPSILON): ('Z', 'T'),
    ('B3,B6,Z', 'A', EPSILON): ('Z', 'A'),

    #B12,Z
    ('B12,Z', 'U', EPSILON): ('C12,Z', 'U'),
    #CARACTERES QUE SÓ Z PEGA
    ('B12,Z', 'K', EPSILON): ('Z', 'K'),
    ('B12,Z', 'O', EPSILON): ('Z', 'O'),
    ('B12,Z', 'L', EPSILON): ('Z', 'L'),
    ('B12,Z', 'H', EPSILON): ('Z', 'H'),
    ('B12,Z', 'N', EPSILON): ('Z', 'N'),
    ('B12,Z', 'J', EPSILON): ('Z', 'J'),
    ('B12,Z', 'F', EPSILON): ('Z', 'F'),
    ('B12,Z', 'S', EPSILON): ('Z', 'S'),
    ('B12,Z', 'I', EPSILON): ('Z', 'I'),
    ('B12,Z', 'M', EPSILON): ('Z', 'M'),
    ('B12,Z', 'D', EPSILON): ('Z', 'D'),
    ('B12,Z', 'R', EPSILON): ('Z', 'R'),
    ('B12,Z', 'T', EPSILON): ('Z', 'T'),
    ('B12,Z', 'A', EPSILON): ('Z', 'A'),

    #B4,Z
    ('B4,Z', 'U', EPSILON): ('C4,Z', 'U'),
    #CARACTERES QUE SÓ Z PEGA
    ('B4,Z', 'K', EPSILON): ('Z', 'K'),
    ('B4,Z', 'O', EPSILON): ('Z', 'O'),
    ('B4,Z', 'E', EPSILON): ('Z', 'E'),
    ('B4,Z', 'L', EPSILON): ('Z', 'L'),
    ('B4,Z', 'H', EPSILON): ('Z', 'H'),
    ('B4,Z', 'N', EPSILON): ('Z', 'N'),
    ('B4,Z', 'J', EPSILON): ('Z', 'J'),
    ('B4,Z', 'F', EPSILON): ('Z', 'F'),
    ('B4,Z', 'S', EPSILON): ('Z', 'S'),
    ('B4,Z', 'I', EPSILON): ('Z', 'I'),
    ('B4,Z', 'M', EPSILON): ('Z', 'M'),
    ('B4,Z', 'D', EPSILON): ('Z', 'D'),
    ('B4,Z', 'R', EPSILON): ('Z', 'R'),
    ('B4,Z', 'T', EPSILON): ('Z', 'T'),
    ('B4,Z', 'A', EPSILON): ('Z', 'A'),

    #B5,B7,B9,Z
    ('B5,B7,B9,Z', 'O', EPSILON): ('C9,Z', 'O'),
    ('B5,B7,B9,Z', 'U', EPSILON): ('C5,Z', 'U'),
    ('B5,B7,B9,Z', 'A', EPSILON): ('C7,Z', 'A'),
    #CARACTERES QUE SÓ Z PEGA
    ('B5,B7,B9,Z', 'K', EPSILON): ('Z', 'K'),
    ('B5,B7,B9,Z', 'E', EPSILON): ('Z', 'E'),
    ('B5,B7,B9,Z', 'L', EPSILON): ('Z', 'L'),
    ('B5,B7,B9,Z', 'H', EPSILON): ('Z', 'H'),
    ('B5,B7,B9,Z', 'N', EPSILON): ('Z', 'N'),
    ('B5,B7,B9,Z', 'J', EPSILON): ('Z', 'J'),
    ('B5,B7,B9,Z', 'F', EPSILON): ('Z', 'F'),
    ('B5,B7,B9,Z', 'S', EPSILON): ('Z', 'S'),
    ('B5,B7,B9,Z', 'I', EPSILON): ('Z', 'I'),
    ('B5,B7,B9,Z', 'M', EPSILON): ('Z', 'M'),
    ('B5,B7,B9,Z', 'D', EPSILON): ('Z', 'D'),
    ('B5,B7,B9,Z', 'R', EPSILON): ('Z', 'R'),
    ('B5,B7,B9,Z', 'T', EPSILON): ('Z', 'T'),


    #B10,B11,Z
    ('B10,B11,Z', 'A', EPSILON): ('C10,Z', 'A'),
    ('B10,B11,Z', 'N', EPSILON): ('C11,Z', 'N'),
    #CARACTERES QUE SÓ Z PEGA
    ('B10,B11,Z', 'K', EPSILON): ('Z', 'K'),
    ('B10,B11,Z', 'O', EPSILON): ('Z', 'O'),
    ('B10,B11,Z', 'E', EPSILON): ('Z', 'E'),
    ('B10,B11,Z', 'L', EPSILON): ('Z', 'L'),
    ('B10,B11,Z', 'H', EPSILON): ('Z', 'H'),
    ('B10,B11,Z', 'J', EPSILON): ('Z', 'J'),
    ('B10,B11,Z', 'U', EPSILON): ('Z', 'U'),
    ('B10,B11,Z', 'F', EPSILON): ('Z', 'F'),
    ('B10,B11,Z', 'S', EPSILON): ('Z', 'S'),
    ('B10,B11,Z', 'I', EPSILON): ('Z', 'I'),
    ('B10,B11,Z', 'M', EPSILON): ('Z', 'M'),
    ('B10,B11,Z', 'D', EPSILON): ('Z', 'D'),
    ('B10,B11,Z', 'R', EPSILON): ('Z', 'R'),
    ('B10,B11,Z', 'T', EPSILON): ('Z', 'T'),

    #B1,Z
    #CARACTERES QUE SÓ Z PEGA
    ('B1,Z', 'K', EPSILON): ('Z', 'K'),
    ('B1,Z', 'O', EPSILON): ('Z', 'O'),
    ('B1,Z', 'E', EPSILON): ('Z', 'E'),
    ('B1,Z', 'L', EPSILON): ('Z', 'L'),
    ('B1,Z', 'H', EPSILON): ('Z', 'H'),
    ('B1,Z', 'N', EPSILON): ('Z', 'N'),
    ('B1,Z', 'J', EPSILON): ('Z', 'J'),
    ('B1,Z', 'U', EPSILON): ('Z', 'U'),
    ('B1,Z', 'F', EPSILON): ('Z', 'F'),
    ('B1,Z', 'S', EPSILON): ('Z', 'S'),
    ('B1,Z', 'I', EPSILON): ('Z', 'I'),
    ('B1,Z', 'M', EPSILON): ('Z', 'M'),
    ('B1,Z', 'D', EPSILON): ('Z', 'D'),
    ('B1,Z', 'R', EPSILON): ('Z', 'R'),
    ('B1,Z', 'T', EPSILON): ('Z', 'T'),
    ('B1,Z', 'A', EPSILON): ('Z', 'A'),

    #C2,Z
    ('C2,Z', 'L', EPSILON): ('D2,Z', 'L'),
    #CARACTERES QUE SÓ Z PEGA
    ('C2,Z', 'K', EPSILON): ('Z', 'K'),
    ('C2,Z', 'O', EPSILON): ('Z', 'O'),
    ('C2,Z', 'E', EPSILON): ('Z', 'E'),
    ('C2,Z', 'H', EPSILON): ('Z', 'H'),
    ('C2,Z', 'N', EPSILON): ('Z', 'N'),
    ('C2,Z', 'J', EPSILON): ('Z', 'J'),
    ('C2,Z', 'F', EPSILON): ('Z', 'F'),
    ('C2,Z', 'S', EPSILON): ('Z', 'S'),
    ('C2,Z', 'I', EPSILON): ('Z', 'I'),
    ('C2,Z', 'M', EPSILON): ('Z', 'M'),
    ('C2,Z', 'D', EPSILON): ('Z', 'D'),
    ('C2,Z', 'R', EPSILON): ('Z', 'R'),
    ('C2,Z', 'T', EPSILON): ('Z', 'T'),
    ('C2,Z', 'A', EPSILON): ('Z', 'A'),
    ('C2,Z', 'U', EPSILON): ('Z', 'U'),

    #C8,Z
    ('C8,Z', 'S', EPSILON): ('D8,Z', 'S'),
    #CARACTERES QUE SÓ Z PEGA
    ('C8,Z', 'O', EPSILON): ('Z', 'O'),
    ('C8,Z', 'E', EPSILON): ('Z', 'E'),
    ('C8,Z', 'K', EPSILON): ('Z', 'K'),
    ('C8,Z', 'L', EPSILON): ('Z', 'L'),
    ('C8,Z', 'H', EPSILON): ('Z', 'H'),
    ('C8,Z', 'N', EPSILON): ('Z', 'N'),
    ('C8,Z', 'J', EPSILON): ('Z', 'J'),
    ('C8,Z', 'U', EPSILON): ('Z', 'U'),
    ('C8,Z', 'F', EPSILON): ('Z', 'F'),
    ('C8,Z', 'I', EPSILON): ('Z', 'I'),
    ('C8,Z', 'M', EPSILON): ('Z', 'M'),
    ('C8,Z', 'D', EPSILON): ('Z', 'D'),
    ('C8,Z', 'R', EPSILON): ('Z', 'R'),
    ('C8,Z', 'T', EPSILON): ('Z', 'T'),
    ('C8,Z', 'A', EPSILON): ('Z', 'A'),

    #C7,Z
    ('C7,Z', 'H', EPSILON): ('D7,Z', 'H'),
    #CARACTERES QUE SÓ Z PEGA
    ('C7,Z', 'O', EPSILON): ('Z', 'O'),
    ('C7,Z', 'E', EPSILON): ('Z', 'E'),
    ('C7,Z', 'K', EPSILON): ('Z', 'K'),
    ('C7,Z', 'L', EPSILON): ('Z', 'L'),
    ('C7,Z', 'S', EPSILON): ('Z', 'S'),
    ('C7,Z', 'N', EPSILON): ('Z', 'N'),
    ('C7,Z', 'J', EPSILON): ('Z', 'J'),
    ('C7,Z', 'U', EPSILON): ('Z', 'U'),
    ('C7,Z', 'F', EPSILON): ('Z', 'F'),
    ('C7,Z', 'I', EPSILON): ('Z', 'I'),
    ('C7,Z', 'M', EPSILON): ('Z', 'M'),
    ('C7,Z', 'D', EPSILON): ('Z', 'D'),
    ('C7,Z', 'R', EPSILON): ('Z', 'R'),
    ('C7,Z', 'T', EPSILON): ('Z', 'T'),
    ('C7,Z', 'A', EPSILON): ('Z', 'A'),

    #B3,Z
    ('B3,Z', 'O', EPSILON): ('B3,Z', 'O'),
    #CARACTERES QUE SÓ Z PEGA
    ('B3,Z', 'E', EPSILON): ('Z', 'E'),
    ('B3,Z', 'K', EPSILON): ('Z', 'K'),
    ('B3,Z', 'L', EPSILON): ('Z', 'L'),
    ('B3,Z', 'H', EPSILON): ('Z', 'H'),
    ('B3,Z', 'N', EPSILON): ('Z', 'N'),
    ('B3,Z', 'J', EPSILON): ('Z', 'J'),
    ('B3,Z', 'U', EPSILON): ('Z', 'U'),
    ('B3,Z', 'F', EPSILON): ('Z', 'F'),
    ('B3,Z', 'I', EPSILON): ('Z', 'I'),
    ('B3,Z', 'M', EPSILON): ('Z', 'M'),
    ('B3,Z', 'D', EPSILON): ('Z', 'D'),
    ('B3,Z', 'R', EPSILON): ('Z', 'R'),
    ('B3,Z', 'T', EPSILON): ('Z', 'T'),
    ('B3,Z', 'A', EPSILON): ('Z', 'A'),

    #C6,Z
    ('C6,Z', 'M', EPSILON): ('D6,Z', 'M'),
    #CARACTERES QUE SÓ Z PEGA
    ('C6,Z', 'O', EPSILON): ('Z', 'O'),
    ('C6,Z', 'E', EPSILON): ('Z', 'E'),
    ('C6,Z', 'K', EPSILON): ('Z', 'K'),
    ('C6,Z', 'L', EPSILON): ('Z', 'L'),
    ('C6,Z', 'H', EPSILON): ('Z', 'H'),
    ('C6,Z', 'N', EPSILON): ('Z', 'N'),
    ('C6,Z', 'J', EPSILON): ('Z', 'J'),
    ('C6,Z', 'U', EPSILON): ('Z', 'U'),
    ('C6,Z', 'F', EPSILON): ('Z', 'F'),
    ('C6,Z', 'I', EPSILON): ('Z', 'I'),
    ('C6,Z', 'D', EPSILON): ('Z', 'D'),
    ('C6,Z', 'R', EPSILON): ('Z', 'R'),
    ('C6,Z', 'T', EPSILON): ('Z', 'T'),
    ('C6,Z', 'A', EPSILON): ('Z', 'A'),

    #C12,Z
    ('C12,Z', 'S', EPSILON): ('D12,Z', 'S'),
    #CARACTERES QUE SÓ Z PEGA
    ('C12,Z', 'O', EPSILON): ('Z', 'O'),
    ('C12,Z', 'E', EPSILON): ('Z', 'E'),
    ('C12,Z', 'K', EPSILON): ('Z', 'K'),
    ('C12,Z', 'L', EPSILON): ('Z', 'L'),
    ('C12,Z', 'H', EPSILON): ('Z', 'H'),
    ('C12,Z', 'N', EPSILON): ('Z', 'N'),
    ('C12,Z', 'J', EPSILON): ('Z', 'J'),
    ('C12,Z', 'U', EPSILON): ('Z', 'U'),
    ('C12,Z', 'F', EPSILON): ('Z', 'F'),
    ('C12,Z', 'I', EPSILON): ('Z', 'I'),
    ('C12,Z', 'M', EPSILON): ('Z', 'M'),
    ('C12,Z', 'D', EPSILON): ('Z', 'D'),
    ('C12,Z', 'R', EPSILON): ('Z', 'R'),
    ('C12,Z', 'T', EPSILON): ('Z', 'T'),
    ('C12,Z', 'A', EPSILON): ('Z', 'A'),

    #C4,Z
    ('C4,Z', 'N', EPSILON): ('D4,Z', 'N'),
    #CARACTERES QUE SÓ Z PEGA
    ('C4,Z', 'O', EPSILON): ('Z', 'O'),
    ('C4,Z', 'E', EPSILON): ('Z', 'E'),
    ('C4,Z', 'K', EPSILON): ('Z', 'K'),
    ('C4,Z', 'L', EPSILON): ('Z', 'L'),
    ('C4,Z', 'H', EPSILON): ('Z', 'H'),
    ('C4,Z', 'J', EPSILON): ('Z', 'J'),
    ('C4,Z', 'U', EPSILON): ('Z', 'U'),
    ('C4,Z', 'F', EPSILON): ('Z', 'F'),
    ('C4,Z', 'I', EPSILON): ('Z', 'I'),
    ('C4,Z', 'M', EPSILON): ('Z', 'M'),
    ('C4,Z', 'D', EPSILON): ('Z', 'D'),
    ('C4,Z', 'R', EPSILON): ('Z', 'R'),
    ('C4,Z', 'T', EPSILON): ('Z', 'T'),
    ('C4,Z', 'A', EPSILON): ('Z', 'A'),

    #C9,Z
    ('C9,Z', 'D', EPSILON): ('D9,Z', 'D'),
    #CARACTERES QUE SÓ Z PEGA
    ('C9,Z', 'O', EPSILON): ('Z', 'O'),
    ('C9,Z', 'E', EPSILON): ('Z', 'E'),
    ('C9,Z', 'K', EPSILON): ('Z', 'K'),
    ('C9,Z', 'L', EPSILON): ('Z', 'L'),
    ('C9,Z', 'H', EPSILON): ('Z', 'H'),
    ('C9,Z', 'N', EPSILON): ('Z', 'N'),
    ('C9,Z', 'J', EPSILON): ('Z', 'J'),
    ('C9,Z', 'U', EPSILON): ('Z', 'U'),
    ('C9,Z', 'F', EPSILON): ('Z', 'F'),
    ('C9,Z', 'I', EPSILON): ('Z', 'I'),
    ('C9,Z', 'M', EPSILON): ('Z', 'M'),
    ('C9,Z', 'R', EPSILON): ('Z', 'R'),
    ('C9,Z', 'T', EPSILON): ('Z', 'T'),
    ('C9,Z', 'A', EPSILON): ('Z', 'A'),

    #C5,Z
    ('C5,Z', 'S', EPSILON): ('D5,Z', 'S'),
    #CARACTERES QUE SÓ Z PEGA
    ('C5,Z', 'O', EPSILON): ('Z', 'O'),
    ('C5,Z', 'E', EPSILON): ('Z', 'E'),
    ('C5,Z', 'K', EPSILON): ('Z', 'K'),
    ('C5,Z', 'L', EPSILON): ('Z', 'L'),
    ('C5,Z', 'H', EPSILON): ('Z', 'H'),
    ('C5,Z', 'N', EPSILON): ('Z', 'N'),
    ('C5,Z', 'J', EPSILON): ('Z', 'J'),
    ('C5,Z', 'U', EPSILON): ('Z', 'U'),
    ('C5,Z', 'F', EPSILON): ('Z', 'F'),
    ('C5,Z', 'I', EPSILON): ('Z', 'I'),
    ('C5,Z', 'M', EPSILON): ('Z', 'M'),
    ('C5,Z', 'D', EPSILON): ('Z', 'D'),
    ('C5,Z', 'R', EPSILON): ('Z', 'R'),
    ('C5,Z', 'T', EPSILON): ('Z', 'T'),
    ('C5,Z', 'A', EPSILON): ('Z', 'A'),

    #B11,Z
    ('B11,Z', 'N', EPSILON): ('C11,Z', 'N'),
    #CARACTERES QUE SÓ Z PEGA
    ('B11,Z', 'O', EPSILON): ('Z', 'O'),
    ('B11,Z', 'E', EPSILON): ('Z', 'E'),
    ('B11,Z', 'K', EPSILON): ('Z', 'K'),
    ('B11,Z', 'L', EPSILON): ('Z', 'L'),
    ('B11,Z', 'H', EPSILON): ('Z', 'H'),
    ('B11,Z', 'N', EPSILON): ('Z', 'N'),
    ('B11,Z', 'J', EPSILON): ('Z', 'J'),
    ('B11,Z', 'U', EPSILON): ('Z', 'U'),
    ('B11,Z', 'F', EPSILON): ('Z', 'F'),
    ('B11,Z', 'I', EPSILON): ('Z', 'I'),
    ('B11,Z', 'M', EPSILON): ('Z', 'M'),
    ('B11,Z', 'D', EPSILON): ('Z', 'D'),
    ('B11,Z', 'R', EPSILON): ('Z', 'R'),
    ('B11,Z', 'T', EPSILON): ('Z', 'T'),
    ('B11,Z', 'A', EPSILON): ('Z', 'A'),

    #B10,Z
    ('B10,Z', 'A', EPSILON): ('C10,Z', 'A'),
    #CARACTERES QUE SÓ Z PEGA
    ('B10,Z', 'O', EPSILON): ('Z', 'O'),
    ('B10,Z', 'E', EPSILON): ('Z', 'E'),
    ('B10,Z', 'K', EPSILON): ('Z', 'K'),
    ('B10,Z', 'L', EPSILON): ('Z', 'L'),
    ('B10,Z', 'H', EPSILON): ('Z', 'H'),
    ('B10,Z', 'N', EPSILON): ('Z', 'N'),
    ('B10,Z', 'J', EPSILON): ('Z', 'J'),
    ('B10,Z', 'U', EPSILON): ('Z', 'U'),
    ('B10,Z', 'F', EPSILON): ('Z', 'F'),
    ('B10,Z', 'I', EPSILON): ('Z', 'I'),
    ('B10,Z', 'M', EPSILON): ('Z', 'M'),
    ('B10,Z', 'D', EPSILON): ('Z', 'D'),
    ('B10,Z', 'R', EPSILON): ('Z', 'R'),
    ('B10,Z', 'T', EPSILON): ('Z', 'T'),
    ('B10,Z', 'A', EPSILON): ('Z', 'A'),

    #D2,Z
    ('D2,Z', 'A', EPSILON): ('Z', 'A'),
    ('D2,Z', 'O', EPSILON): ('Z', 'O'),
    ('D2,Z', 'E', EPSILON): ('Z', 'E'),
    ('D2,Z', 'K', EPSILON): ('Z', 'K'),
    ('D2,Z', 'L', EPSILON): ('Z', 'L'),
    ('D2,Z', 'H', EPSILON): ('Z', 'H'),
    ('D2,Z', 'N', EPSILON): ('Z', 'N'),
    ('D2,Z', 'J', EPSILON): ('Z', 'J'),
    ('D2,Z', 'U', EPSILON): ('Z', 'U'),
    ('D2,Z', 'F', EPSILON): ('Z', 'F'),
    ('D2,Z', 'I', EPSILON): ('Z', 'I'),
    ('D2,Z', 'M', EPSILON): ('Z', 'M'),
    ('D2,Z', 'D', EPSILON): ('Z', 'D'),
    ('D2,Z', 'R', EPSILON): ('Z', 'R'),
    ('D2,Z', 'T', EPSILON): ('Z', 'T'),
    ('D2,Z', 'A', EPSILON): ('Z', 'A'),

    #D8,Z
    ('D8,Z', 'A', EPSILON): ('Z', 'A'),
    ('D8,Z', 'O', EPSILON): ('Z', 'O'),
    ('D8,Z', 'E', EPSILON): ('Z', 'E'),
    ('D8,Z', 'K', EPSILON): ('Z', 'K'),
    ('D8,Z', 'L', EPSILON): ('Z', 'L'),
    ('D8,Z', 'H', EPSILON): ('Z', 'H'),
    ('D8,Z', 'N', EPSILON): ('Z', 'N'),
    ('D8,Z', 'J', EPSILON): ('Z', 'J'),
    ('D8,Z', 'U', EPSILON): ('Z', 'U'),
    ('D8,Z', 'F', EPSILON): ('Z', 'F'),
    ('D8,Z', 'I', EPSILON): ('Z', 'I'),
    ('D8,Z', 'M', EPSILON): ('Z', 'M'),
    ('D8,Z', 'D', EPSILON): ('Z', 'D'),
    ('D8,Z', 'R', EPSILON): ('Z', 'R'),
    ('D8,Z', 'T', EPSILON): ('Z', 'T'),
    ('D8,Z', 'A', EPSILON): ('Z', 'A'),

    #D7,Z
    ('D7,Z', 'A', EPSILON): ('Z', 'A'),
    ('D7,Z', 'O', EPSILON): ('Z', 'O'),
    ('D7,Z', 'E', EPSILON): ('Z', 'E'),
    ('D7,Z', 'K', EPSILON): ('Z', 'K'),
    ('D7,Z', 'L', EPSILON): ('Z', 'L'),
    ('D7,Z', 'H', EPSILON): ('Z', 'H'),
    ('D7,Z', 'N', EPSILON): ('Z', 'N'),
    ('D7,Z', 'J', EPSILON): ('Z', 'J'),
    ('D7,Z', 'U', EPSILON): ('Z', 'U'),
    ('D7,Z', 'F', EPSILON): ('Z', 'F'),
    ('D7,Z', 'I', EPSILON): ('Z', 'I'),
    ('D7,Z', 'M', EPSILON): ('Z', 'M'),
    ('D7,Z', 'D', EPSILON): ('Z', 'D'),
    ('D7,Z', 'R', EPSILON): ('Z', 'R'),
    ('D7,Z', 'T', EPSILON): ('Z', 'T'),
    ('D7,Z', 'A', EPSILON): ('Z', 'A'),

    #C3,Z
    ('C3,Z', 'N', EPSILON): ('D3,Z', 'N'),
    #CARACTERES QUE SÓ Z PEGA
    ('C3,Z', 'O', EPSILON): ('Z', 'O'),
    ('C3,Z', 'E', EPSILON): ('Z', 'E'),
    ('C3,Z', 'K', EPSILON): ('Z', 'K'),
    ('C3,Z', 'L', EPSILON): ('Z', 'L'),
    ('C3,Z', 'H', EPSILON): ('Z', 'H'),
    ('C3,Z', 'J', EPSILON): ('Z', 'J'),
    ('C3,Z', 'U', EPSILON): ('Z', 'U'),
    ('C3,Z', 'F', EPSILON): ('Z', 'F'),
    ('C3,Z', 'I', EPSILON): ('Z', 'I'),
    ('C3,Z', 'M', EPSILON): ('Z', 'M'),
    ('C3,Z', 'D', EPSILON): ('Z', 'D'),
    ('C3,Z', 'R', EPSILON): ('Z', 'R'),
    ('C3,Z', 'T', EPSILON): ('Z', 'T'),
    ('C3,Z', 'A', EPSILON): ('Z', 'A'),

    #D6,Z
    ('D6,Z', 'A', EPSILON): ('Z', 'A'),
    ('D6,Z', 'O', EPSILON): ('Z', 'O'),
    ('D6,Z', 'E', EPSILON): ('Z', 'E'),
    ('D6,Z', 'K', EPSILON): ('Z', 'K'),
    ('D6,Z', 'L', EPSILON): ('Z', 'L'),
    ('D6,Z', 'H', EPSILON): ('Z', 'H'),
    ('D6,Z', 'N', EPSILON): ('Z', 'N'),
    ('D6,Z', 'J', EPSILON): ('Z', 'J'),
    ('D6,Z', 'U', EPSILON): ('Z', 'U'),
    ('D6,Z', 'F', EPSILON): ('Z', 'F'),
    ('D6,Z', 'I', EPSILON): ('Z', 'I'),
    ('D6,Z', 'M', EPSILON): ('Z', 'M'),
    ('D6,Z', 'D', EPSILON): ('Z', 'D'),
    ('D6,Z', 'R', EPSILON): ('Z', 'R'),
    ('D6,Z', 'T', EPSILON): ('Z', 'T'),
    ('D6,Z', 'A', EPSILON): ('Z', 'A'),

    #D12,Z
    ('D12,Z', 'T', EPSILON): ('E12,Z', 'T'),
    #CARACTERES QUE SÓ Z PEGA
    ('D12,Z', 'A', EPSILON): ('Z', 'A'),
    ('D12,Z', 'O', EPSILON): ('Z', 'O'),
    ('D12,Z', 'E', EPSILON): ('Z', 'E'),
    ('D12,Z', 'K', EPSILON): ('Z', 'K'),
    ('D12,Z', 'L', EPSILON): ('Z', 'L'),
    ('D12,Z', 'H', EPSILON): ('Z', 'H'),
    ('D12,Z', 'N', EPSILON): ('Z', 'N'),
    ('D12,Z', 'J', EPSILON): ('Z', 'J'),
    ('D12,Z', 'U', EPSILON): ('Z', 'U'),
    ('D12,Z', 'F', EPSILON): ('Z', 'F'),
    ('D12,Z', 'I', EPSILON): ('Z', 'I'),
    ('D12,Z', 'M', EPSILON): ('Z', 'M'),
    ('D12,Z', 'D', EPSILON): ('Z', 'D'),
    ('D12,Z', 'R', EPSILON): ('Z', 'R'),

    #D4,Z
    ('D4,Z', 'A', EPSILON): ('Z', 'A'),
    ('D4,Z', 'O', EPSILON): ('Z', 'O'),
    ('D4,Z', 'E', EPSILON): ('Z', 'E'),
    ('D4,Z', 'K', EPSILON): ('Z', 'K'),
    ('D4,Z', 'L', EPSILON): ('Z', 'L'),
    ('D4,Z', 'H', EPSILON): ('Z', 'H'),
    ('D4,Z', 'N', EPSILON): ('Z', 'N'),
    ('D4,Z', 'J', EPSILON): ('Z', 'J'),
    ('D4,Z', 'U', EPSILON): ('Z', 'U'),
    ('D4,Z', 'F', EPSILON): ('Z', 'F'),
    ('D4,Z', 'I', EPSILON): ('Z', 'I'),
    ('D4,Z', 'M', EPSILON): ('Z', 'M'),
    ('D4,Z', 'D', EPSILON): ('Z', 'D'),
    ('D4,Z', 'R', EPSILON): ('Z', 'R'),
    ('D4,Z', 'T', EPSILON): ('Z', 'T'),
    ('D4,Z', 'A', EPSILON): ('Z', 'A'),

    #D9,Z
    ('D9,Z', 'A', EPSILON): ('Z', 'A'),
    ('D9,Z', 'O', EPSILON): ('Z', 'O'),
    ('D9,Z', 'E', EPSILON): ('Z', 'E'),
    ('D9,Z', 'K', EPSILON): ('Z', 'K'),
    ('D9,Z', 'L', EPSILON): ('Z', 'L'),
    ('D9,Z', 'H', EPSILON): ('Z', 'H'),
    ('D9,Z', 'N', EPSILON): ('Z', 'N'),
    ('D9,Z', 'J', EPSILON): ('Z', 'J'),
    ('D9,Z', 'U', EPSILON): ('Z', 'U'),
    ('D9,Z', 'F', EPSILON): ('Z', 'F'),
    ('D9,Z', 'I', EPSILON): ('Z', 'I'),
    ('D9,Z', 'M', EPSILON): ('Z', 'M'),
    ('D9,Z', 'D', EPSILON): ('Z', 'D'),
    ('D9,Z', 'R', EPSILON): ('Z', 'R'),
    ('D9,Z', 'T', EPSILON): ('Z', 'T'),
    ('D9,Z', 'A', EPSILON): ('Z', 'A'),

    #D5,Z
    ('D5,Z', 'A', EPSILON): ('Z', 'A'),
    ('D5,Z', 'O', EPSILON): ('Z', 'O'),
    ('D5,Z', 'E', EPSILON): ('Z', 'E'),
    ('D5,Z', 'K', EPSILON): ('Z', 'K'),
    ('D5,Z', 'L', EPSILON): ('Z', 'L'),
    ('D5,Z', 'H', EPSILON): ('Z', 'H'),
    ('D5,Z', 'N', EPSILON): ('Z', 'N'),
    ('D5,Z', 'J', EPSILON): ('Z', 'J'),
    ('D5,Z', 'U', EPSILON): ('Z', 'U'),
    ('D5,Z', 'F', EPSILON): ('Z', 'F'),
    ('D5,Z', 'I', EPSILON): ('Z', 'I'),
    ('D5,Z', 'M', EPSILON): ('Z', 'M'),
    ('D5,Z', 'D', EPSILON): ('Z', 'D'),
    ('D5,Z', 'R', EPSILON): ('Z', 'R'),
    ('D5,Z', 'T', EPSILON): ('Z', 'T'),
    ('D5,Z', 'A', EPSILON): ('Z', 'A'),

    #C11,Z
    ('C11,Z', 'R', EPSILON): ('D11,Z', 'R'),
    #CARACTERES QUE SÓ Z PEGA
    ('C11,Z', 'A', EPSILON): ('Z', 'A'),
    ('C11,Z', 'O', EPSILON): ('Z', 'O'),
    ('C11,Z', 'E', EPSILON): ('Z', 'E'),
    ('C11,Z', 'K', EPSILON): ('Z', 'K'),
    ('C11,Z', 'L', EPSILON): ('Z', 'L'),
    ('C11,Z', 'H', EPSILON): ('Z', 'H'),
    ('C11,Z', 'N', EPSILON): ('Z', 'N'),
    ('C11,Z', 'J', EPSILON): ('Z', 'J'),
    ('C11,Z', 'U', EPSILON): ('Z', 'U'),
    ('C11,Z', 'F', EPSILON): ('Z', 'F'),
    ('C11,Z', 'I', EPSILON): ('Z', 'I'),
    ('C11,Z', 'M', EPSILON): ('Z', 'M'),
    ('C11,Z', 'D', EPSILON): ('Z', 'D'),
    ('C11,Z', 'T', EPSILON): ('Z', 'T'),
    ('C11,Z', 'A', EPSILON): ('Z', 'A'),

    #C10,Z
    ('C10,Z', 'N', EPSILON): ('D10,Z', 'N'),
    #CARACTERES QUE SÓ Z PEGA
    ('C10,Z', 'A', EPSILON): ('Z', 'A'),
    ('C10,Z', 'O', EPSILON): ('Z', 'O'),
    ('C10,Z', 'E', EPSILON): ('Z', 'E'),
    ('C10,Z', 'K', EPSILON): ('Z', 'K'),
    ('C10,Z', 'L', EPSILON): ('Z', 'L'),
    ('C10,Z', 'H', EPSILON): ('Z', 'H'),
    ('C10,Z', 'J', EPSILON): ('Z', 'J'),
    ('C10,Z', 'U', EPSILON): ('Z', 'U'),
    ('C10,Z', 'F', EPSILON): ('Z', 'F'),
    ('C10,Z', 'I', EPSILON): ('Z', 'I'),
    ('C10,Z', 'M', EPSILON): ('Z', 'M'),
    ('C10,Z', 'D', EPSILON): ('Z', 'D'),
    ('C10,Z', 'R', EPSILON): ('Z', 'R'),
    ('C10,Z', 'T', EPSILON): ('Z', 'T'),

    #D3,Z
    ('D3,Z', 'A', EPSILON): ('Z', 'A'),
    ('D3,Z', 'O', EPSILON): ('Z', 'O'),
    ('D3,Z', 'E', EPSILON): ('Z', 'E'),
    ('D3,Z', 'K', EPSILON): ('Z', 'K'),
    ('D3,Z', 'L', EPSILON): ('Z', 'L'),
    ('D3,Z', 'H', EPSILON): ('Z', 'H'),
    ('D3,Z', 'N', EPSILON): ('Z', 'N'),
    ('D3,Z', 'J', EPSILON): ('Z', 'J'),
    ('D3,Z', 'U', EPSILON): ('Z', 'U'),
    ('D3,Z', 'F', EPSILON): ('Z', 'F'),
    ('D3,Z', 'I', EPSILON): ('Z', 'I'),
    ('D3,Z', 'M', EPSILON): ('Z', 'M'),
    ('D3,Z', 'D', EPSILON): ('Z', 'D'),
    ('D3,Z', 'R', EPSILON): ('Z', 'R'),
    ('D3,Z', 'T', EPSILON): ('Z', 'T'),
    ('D3,Z', 'A', EPSILON): ('Z', 'A'),

    #E12,Z
    ('E12,Z', 'A', EPSILON): ('Z', 'A'),
    ('E12,Z', 'O', EPSILON): ('Z', 'O'),
    ('E12,Z', 'E', EPSILON): ('Z', 'E'),
    ('E12,Z', 'K', EPSILON): ('Z', 'K'),
    ('E12,Z', 'L', EPSILON): ('Z', 'L'),
    ('E12,Z', 'H', EPSILON): ('Z', 'H'),
    ('E12,Z', 'N', EPSILON): ('Z', 'N'),
    ('E12,Z', 'J', EPSILON): ('Z', 'J'),
    ('E12,Z', 'U', EPSILON): ('Z', 'U'),
    ('E12,Z', 'F', EPSILON): ('Z', 'F'),
    ('E12,Z', 'I', EPSILON): ('Z', 'I'),
    ('E12,Z', 'M', EPSILON): ('Z', 'M'),
    ('E12,Z', 'D', EPSILON): ('Z', 'D'),
    ('E12,Z', 'R', EPSILON): ('Z', 'R'),
    ('E12,Z', 'T', EPSILON): ('Z', 'T'),
    ('E12,Z', 'A', EPSILON): ('Z', 'A'),

    #D11,Z
    ('D11,Z', 'K', EPSILON): ('E11,Z', 'K'),
    #CARACTERES QUE SÓ Z PEGA
    ('D11,Z', 'A', EPSILON): ('Z', 'A'),
    ('D11,Z', 'O', EPSILON): ('Z', 'O'),
    ('D11,Z', 'E', EPSILON): ('Z', 'E'),
    ('D11,Z', 'L', EPSILON): ('Z', 'L'),
    ('D11,Z', 'H', EPSILON): ('Z', 'H'),
    ('D11,Z', 'N', EPSILON): ('Z', 'N'),
    ('D11,Z', 'J', EPSILON): ('Z', 'J'),
    ('D11,Z', 'U', EPSILON): ('Z', 'U'),
    ('D11,Z', 'F', EPSILON): ('Z', 'F'),
    ('D11,Z', 'I', EPSILON): ('Z', 'I'),
    ('D11,Z', 'M', EPSILON): ('Z', 'M'),
    ('D11,Z', 'D', EPSILON): ('Z', 'D'),
    ('D11,Z', 'R', EPSILON): ('Z', 'R'),
    ('D11,Z', 'T', EPSILON): ('Z', 'T'),

    #D10,Z
    ('D10,Z', 'A', EPSILON): ('Z', 'A'),
    ('D10,Z', 'O', EPSILON): ('Z', 'O'),
    ('D10,Z', 'E', EPSILON): ('Z', 'E'),
    ('D10,Z', 'K', EPSILON): ('Z', 'K'),
    ('D10,Z', 'L', EPSILON): ('Z', 'L'),
    ('D10,Z', 'H', EPSILON): ('Z', 'H'),
    ('D10,Z', 'N', EPSILON): ('Z', 'N'),
    ('D10,Z', 'J', EPSILON): ('Z', 'J'),
    ('D10,Z', 'U', EPSILON): ('Z', 'U'),
    ('D10,Z', 'F', EPSILON): ('Z', 'F'),
    ('D10,Z', 'I', EPSILON): ('Z', 'I'),
    ('D10,Z', 'M', EPSILON): ('Z', 'M'),
    ('D10,Z', 'D', EPSILON): ('Z', 'D'),
    ('D10,Z', 'R', EPSILON): ('Z', 'R'),
    ('D10,Z', 'T', EPSILON): ('Z', 'T'),
    ('D10,Z', 'A', EPSILON): ('Z', 'A'),

    #E11,Z
    #CARACTERES QUE SÓ Z PEGA
    ('E11,Z', 'O', EPSILON): ('Z', 'O'),
    ('E11,Z', 'E', EPSILON): ('Z', 'E'),
    ('E11,Z', 'K', EPSILON): ('Z', 'K'),
    ('E11,Z', 'L', EPSILON): ('Z', 'L'),
    ('E11,Z', 'H', EPSILON): ('Z', 'H'),
    ('E11,Z', 'N', EPSILON): ('Z', 'N'),
    ('E11,Z', 'J', EPSILON): ('Z', 'J'),
    ('E11,Z', 'U', EPSILON): ('Z', 'U'),
    ('E11,Z', 'F', EPSILON): ('Z', 'F'),
    ('E11,Z', 'I', EPSILON): ('Z', 'I'),
    ('E11,Z', 'M', EPSILON): ('Z', 'M'),
    ('E11,Z', 'D', EPSILON): ('Z', 'D'),
    ('E11,Z', 'R', EPSILON): ('Z', 'R'),
    ('E11,Z', 'T', EPSILON): ('Z', 'T'),
    ('E11,Z', 'A', EPSILON): ('Z', 'A'),    

}