closures = {
    0: {
        ("S'", (".", "S")),
        ("S", (".", "CMD", ";", "S")),
        ("S", (".", "CMD")),
        ("CMD", (".", "LOS", "EXPR", "CMD")),
        ("CMD", (".", "FOD", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "FAH", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "IO", "id")),
        ("CMD", (".", "JUN", "EXPR")),
        ("CMD", (".", "LHS", ":=", "EXPR")),
        ("CMD", (".", "KEL", "id", "CMD")),
        ("CMD", (".", "FUS", "id", ":=", "EXPR")),
        ("IO", (".", "HON")),
        ("IO", (".", "print")),
        ("LHS", (".", "assign", "id")),
        ("LHS", (".", "HIM", ".", "id")),
    },

    1: {
        ("S'", ("S", ".")),
    },

    2: {
        ("S", ("CMD", ".", ";", "S")),
        ("S", ("CMD", ".")),
    },

    3: {
        ("CMD", ("LOS", ".", "EXPR", "CMD")),
        ("EXPR", (".", "TERM", "EXPR'")),
        ("TERM", (".", "UNARY")),
        ("TERM", (".", "FACTOR")),
        ("UNARY", (".", "NUST", "TERM")),
        ("FACTOR", (".", "id")),
        ("FACTOR", (".", "num")),
        ("FACTOR", (".", "HIM", ".", "id")),
        ("FACTOR", (".", "(", "EXPR", ")")),
    },

    4: {
        ("CMD", ("FOD", ".", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "LOS", "EXPR", "CMD")),
        ("CMD", (".", "FOD", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "FAH", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "IO", "id")),
        ("CMD", (".", "JUN", "EXPR")),
        ("CMD", (".", "LHS", ":=", "EXPR")),
        ("CMD", (".", "KEL", "id", "CMD")),
        ("CMD", (".", "FUS", "id", ":=", "EXPR")),
        ("IO", (".", "HON")),
        ("IO", (".", "print")),
        ("LHS", (".", "assign", "id")),
        ("LHS", (".", "HIM", ".", "id")),
    },

    5: {
        ("CMD", ("FAH", ".", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "LOS", "EXPR", "CMD")),
        ("CMD", (".", "FOD", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "FAH", "CMD", "FAH", "EXPR")),
        ("CMD", (".", "IO", "id")),
        ("CMD", (".", "JUN", "EXPR")),
        ("CMD", (".", "LHS", ":=", "EXPR")),
        ("CMD", (".", "KEL", "id", "CMD")),
        ("CMD", (".", "FUS", "id", ":=", "EXPR")),
        ("IO", (".", "HON")),
        ("IO", (".", "print")),
        ("LHS", (".", "assign", "id")),
        ("LHS", (".", "HIM", ".", "id")),
    },

    6: {
        ("CMD", ("IO", ".", "id")),
    },

    7: {
        ("CMD", ("JUN", ".", "EXPR")),
        ("EXPR", (".", "TERM", "EXPR'")),
        ("TERM", (".", "UNARY")),
        ("TERM", (".", "FACTOR")),
        ("UNARY", (".", "NUST", "TERM")),
        ("FACTOR", (".", "id")),
        ("FACTOR", (".", "num")),
        ("FACTOR", (".", "HIM", ".", "id")),
        ("FACTOR", (".", "(", "EXPR", ")")),
    },

    8: {
        ("CMD", ("LHS", ".", ":=", "EXPR")),
    },

    9: {
        ("CMD", ("KEL", ".", "id", "CMD")),
    },

    10: {
        ("CMD", ("FUS", ".", "id", ":=", "EXPR")),
    },
    11: ["IO -> HON."],
    12: ["IO -> print."],
    13: ["LHS -> assign.id"],
    14: ["LHS -> HIM. id"],  
    15: [
        "S -> CMD ;.S",
        "S -> .CMD ; S",
        "S -> .CMD",
        "CMD -> .LOS EXPR CMD",
        "CMD -> .FOD CMD FAH EXPR",
        "CMD -> .FAH CMD FAH EXPR",
        "CMD -> .IO id",
        "CMD -> .JUN EXPR",
        "CMD -> .LHS := EXPR",
        "CMD -> .KEL id CMD",
        "CMD -> .FUS id := EXPR",
        "IO -> .HON",
        "IO -> .print",
        "LHS -> .assign id",
        "LHS -> .HIM . id"
    ],
    16: [
        "CMD -> LOS EXPR.CMD",
        "CMD -> .LOS EXPR CMD",
        "CMD -> .FOD CMD FAH EXPR",
        "CMD -> .FAH CMD FAH EXPR",
        "CMD -> .IO id",
        "CMD -> .JUN EXPR",
        "CMD -> .LHS := EXPR",
        "CMD -> .KEL id CMD",
        "CMD -> .FUS id := EXPR",
        "IO -> .HON",
        "IO -> .print",
        "LHS -> .assign id",
        "LHS -> .HIM . id"
    ],
    17: [
        "EXPR -> TERM.EXPR'",
        "EXPR' -> .OP TERM EXPR'",
        "EXPR' -> .ε",
        "OP -> .+",
        "OP -> .-",
        "OP -> .ANRK",
        "OP -> .AAN",
        "OP -> .KO"
    ],
    18: ["TERM -> UNARY."],
    19: ["TERM -> FACTOR."],
    20: [
        "UNARY -> NUST.TERM",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    21: ["FACTOR -> id."],
    22: ["FACTOR -> num."],
    23: ["FACTOR -> HIM. id"],  # confirmar se realmente há dois pontos
    24: [
        "FACTOR -> (.EXPR )",
        "EXPR -> .TERM EXPR'",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    25: ["CMD -> FOD CMD.FAH EXPR"],
    26: ["CMD -> FAH CMD.FAH EXPR"],
    27: ["CMD -> IO id."],
    28: ["CMD -> JUN EXPR."],
    29: [
        "CMD -> LHS :=.EXPR",
        "EXPR -> .TERM EXPR'",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    30: [
        "CMD -> KEL id.CMD",
        "CMD -> .LOS EXPR CMD",
        "CMD -> .FOD CMD FAH EXPR",
        "CMD -> .FAH CMD FAH EXPR",
        "CMD -> .IO id",
        "CMD -> .JUN EXPR",
        "CMD -> .LHS := EXPR",
        "CMD -> .KEL id CMD",
        "CMD -> .FUS id := EXPR",
        "IO -> .HON",
        "IO -> .print",
        "LHS -> .assign id",
        "LHS -> .HIM . id"
    ],
    31: ["CMD -> FUS id.:= EXPR"],
    32: ["LHS -> assign id."],
    33: ["LHS -> HIM. id"],  # confirmar se é mesmo '..' ou erro de digitação
    34: ["S -> CMD ; S."],
    35: ["CMD -> LOS EXPR CMD."],
    36: ["EXPR -> TERM EXPR'."],
    37: [
        "EXPR' -> OP.TERM EXPR'",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    38: ["EXPR' -> ε."],
    39: ["OP -> +."],
    40: ["OP -> -."],
    41: ["OP -> ANRK."],
    42: ["OP -> AAN."],
    43: ["OP -> KO."],
    44: ["UNARY -> NUST TERM."],
    45: ["FACTOR -> HIM .id"],  # provavelmente deveria ser "HIM . id"
    46: ["FACTOR -> ( EXPR.)"],
    47: [
        "CMD -> FOD CMD FAH.EXPR",
        "EXPR -> .TERM EXPR'",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    48: [
        "CMD -> FAH CMD FAH.EXPR",
        "EXPR -> .TERM EXPR'",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    49: ["CMD -> LHS := EXPR."],
    50: ["CMD -> KEL id CMD."],
    51: [
        "CMD -> FUS id :=.EXPR",
        "EXPR -> .TERM EXPR'",
        "TERM -> .UNARY",
        "TERM -> .FACTOR",
        "UNARY -> .NUST TERM",
        "FACTOR -> .id",
        "FACTOR -> .num",
        "FACTOR -> .HIM . id",
        "FACTOR -> .( EXPR )"
    ],
    52: ["LHS -> HIM . id."],
    53: [
        "EXPR' -> OP TERM.EXPR'",
        "EXPR' -> .OP TERM EXPR'",
        "EXPR' -> .ε",
        "OP -> .+",
        "OP -> .-",
        "OP -> .ANRK",
        "OP -> .AAN",
        "OP -> .KO"
    ],
    54: ["FACTOR -> HIM . id."],
    55: ["FACTOR -> ( EXPR )."],
    56: ["CMD -> FOD CMD FAH EXPR."],
    57: ["CMD -> FAH CMD FAH EXPR."],
    58: ["CMD -> FUS id := EXPR."],
    59: ["EXPR' -> OP TERM EXPR'."]
}
